matrix:
    include:
        - language: c
          script:
                # bash
              - cd bash
              - ./hello
              - cd ..
                # C
              - cd c
              - make
              - ./hello
              - cd ..
                # C++
              - cd cpp
              - make && ./hello
              - cd ..
                # Perl5
              - cd perl5
              - perl hello.pl
              - cd ..
                # Python2
              - cd python2
              - python hello.py
              - cd ..
                # Python3
              - cd python3
              - python3 hello.py
              - cd ..

        - language: ruby
          rvm: 2.5.1
          script:
                # Rails
              - cd rails
              - bundle install
              - rails test
              - cd ..
        - language: rust
          script:
                # Rust
              - cd rust
              - cargo run
              - cd ..

